logins_and_alerts/urls.py
from django.urls import path

from . import views

app_name = 'loginsapp' 
urlpatterns = [
    path("signin/", views.loginuser, name="loginuser"),
    path("signout/", views.logoutuser, name="logoutuser"),
    path("register/", views.registeruser, name="registeruser"),
    path("update/", views.updateuser, name="updateuser"),
    path("adddrone/", views.registerdrone, name="adddrone"),
    path("updatedrone/<str:dronetarget>", views.updatedrone, name="updatedrone"),
    path("deletedrone/<str:dronetarget>", views.deletedrone, name="deletedrone"),
    path("test/", views.testhtml, name="testhtml"),
]

medidronebackend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newstuff.urls', namespace='homeapp')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('logins_and_alerts.urls', namespace='loginsapp')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newstuff/urls.py
from django.urls import path,include

from . import views

app_name = 'homeapp' 
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("template/", views.template, name="template"),
    path("alerts/", views.alerts, name="alerts"),
    path("reports/", views.reports, name="reports"),
    path("team/", views.team, name="team"),
    path("settings/", views.settings, name="settings"),
    path("drones/", views.drones, name="drones"),
    path("profile/<str:username>", views.profile, name="profile"),
    path("maketeam/<str:targetuser>", views.maketeam, name="maketeam"),
    path("makestaff/<str:targetuser>", views.makestaff, name="makestaff"),
    path("removeteam/<str:targetuser>", views.removeteam, name="removeteam"),
    path("removestaff/<str:targetuser>", views.removestaff, name="removestaff"),
] 

newstuff/models.py
from django.db import models

# Create your models here.

newstuff/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.contrib.auth.decorators import login_required
from logins_and_alerts.models import Drone, CUser, Alert, Report
from django.contrib import messages
from django.contrib.auth.models import User
from time import gmtime, strftime

user_list = CUser.objects.all()  
drone_list = Drone.objects.all()
alerts_list = Alert.objects.all()
unread_alerts = 0
drone_active = 0
drone_not_active = 0
team_members = 0

def reloadlists():
    global user_list
    global drone_list
    global alerts_list
    global reports_list
    presortedalerts = Alert.objects.all()
    presortedreports = Report.objects.all()
    user_list = CUser.objects.all()  
    drone_list = Drone.objects.all()
    alerts_list = presortedalerts.order_by('timeofalert')
    reports_list = presortedreports.order_by('timeofreport')

def getdrones():
    reloadlists()
    global drone_active
    global drone_not_active
    drone_active = 0
    drone_not_active = 0
    for drone in drone_list:
        if drone.active:
            drone_active = drone_active + 1
        else:
            drone_not_active = drone_not_active + 1

def getunreadalerts():
    reloadlists()
    global unread_alerts
    unread_alerts = 0
    for alert in alerts_list:
        if not alert.is_read:
            unread_alerts = unread_alerts + 1

def getteam():
    reloadlists()
    global team_members
    team_members = 0
    for user in user_list:
        if user.is_in_team:
            team_members = team_members + 1

def dashboard(request):   
    getdrones()
    getunreadalerts()
    # User_instance = User.objects.create(user=current_user)
    return render(request, 'home.html', {'drone_active': drone_active, 'drone_not_active': drone_not_active, 'drone_list': drone_list, 'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request, 'currenttime':strftime("%b. %d, %Y", gmtime()), 'reports_list': reports_list})
 
def template(request):
    getunreadalerts()
    return render(request, "empty.html", {'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request})


def drones(request):
    getdrones()
    getunreadalerts()
    return render(request, "drones.html", {'drone_list': drone_list, 'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request})


def alerts(request): 
    getunreadalerts()
    return render(request, "alerts.html", {'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request, 'alerts_list': alerts_list})

def reports(request): 
    getunreadalerts()
    return render(request, "reports.html", {'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request, 'reports_list': reports_list})

def team(request): 
    getunreadalerts()
    return render(request, "team.html", {'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request})

def settings(request):
    getunreadalerts()
    return render(request, "settings.html", {'unread_alerts': unread_alerts, 'user_list': user_list, 'request': request})       

def profile(request,username): 
    reloadlists()
    target = ''
    for user in user_list:
        if username == user.username:
            target = user
    return render(request, "profile.html", {'user_list': user_list, 'target': target})        


def maketeam(request, targetuser):
    reloadlists()
    for user in user_list:
        if targetuser == user.username:
            target = user
    target.is_in_team = True
    target.save()
    messages.success(request, (target.username + " has join the Team."))
    return redirect('homeapp:profile', username = target)

def makestaff(request, targetuser):
    reloadlists()
    for user in user_list:
        if targetuser == user.username:
            target = user
    target.is_staff = True
    target.save()
    messages.success(request, (target.username + " has join the Staff team."))
    return redirect('homeapp:profile', username = target)

def removeteam(request, targetuser):
    reloadlists()
    for user in user_list:
        if targetuser == user.username:
            target = user
    target.is_in_team = False
    target.save()
    messages.success(request, (target.username + " has been removed from the Team."))
    return redirect('homeapp:profile', username = target)

def removestaff(request, targetuser):
    reloadlists()
    for user in user_list:
        if targetuser == user.username:
            target = user
    target.is_staff = False
    target.save()
    messages.success(request, (target.username + " has been removed from the Staff team."))
    return redirect('homeapp:profile', username = target)
       

newstuff/templates/alerts.html
{% extends "base.html" %}

{% load static %}

{% block style %}
    <style>
        body {
            font-family: "Poppins", sans-serif;
        }

        .container {
            padding: 20px;
        }

        .background-container {
            background-size: cover;
            background-position: center center;
            height: 650px;
            width: 1100px;
            margin: 50px auto;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 10px;
            position: relative;
        }

        .transparent-card {
            width: 990px;
            height: 680px;
            background: rgba(255, 255, 255, 0.7);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            position: relative;
            overflow: hidden;
        }

        .accordion-item {
            padding-top: 20px;
            background: #ffffff00;
            color: #ffffff00;
            border-color: #ffffff00;
        }

        .accordion-body{
            background: #ffffff;
            border-color: #ffffff00;
            color:#000000;
        }

        .accordion-button:not(.collapsed) {
            color: #000000;
            background-color: #ffffff;
            box-shadow: inset 0 -1px 0 rgba(0, 0, 0, .125);
        }    

        .wrapper {
            width: 820px;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .toast {
            width: 100%;
            height: 80px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 7px;
            display: grid;
            grid-template-columns: 1.3fr 6fr 0.5fr;
            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.08);
        }

        .toast:not(:last-child) {
            margin-bottom: 20px;
        }

        .outer-container, .inner-container {
            align-self: center;
        }

        .outer-container i {
            font-size: 24px; /* Adjusted font size for icons */
        }

        .inner-container p:first-child {
            color: #101020;
            font-weight: 600;
            font-size: 20px;
        }

        .inner-container p:last-child {
            font-size: 14px;
            font-weight: 400;
            color: #656565;
        }

        .toast button {
            align-self: flex-start;
            background-color: transparent;
            font-size: 20px;
            color: #656565;
            line-height: 0;
            cursor: pointer;
            padding: 10px;
            margin-right: -10px;
        }

        .success {
            border-left: 5px solid #47D764;
        }

        .error {
            border-left: 5px solid #ff355b;
        }

        .info {
            border-left: 5px solid #2F86EB;
        }

        .warning {
            border-left: 5px solid #FFC021;
        }

        .success i {
            color: #47D764;
        }

        .error i {
            color: #ff355b;
        }

        .info i {
            color: #2F86EB;
        }

        .warning i {
            color: #FFC021;
        }

        .customtop {
            top: 12.5%;
            left: 99.3%;
        }
    </style>
{% endblock %}

{% block darktheme %}
    <style>
        .transparent-card {
            width: 990px;
            height: 680px;
            background: #000000b3;
            box-shadow: 0 4px 8px #FFFFFF1a;
            border-radius: 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            position: relative;
            overflow: hidden;
        }

        .accordion-item {
            padding-top: 20px;
            background: #ffffff00;
            color: #ffffff00;
            border-color: #ffffff00;
        }

        .accordion-body{
            background: #000000;
            border-color: #00000000;
            color:#FFFFFF;
        }

        .accordion-button:not(.collapsed) {
            color: #FFFFFF;
            background-color: #000000;
            box-shadow: inset 0 -1px 0 rgba(0, 0, 0, .125);
        }    

        .toast {
            width: 100%;
            height: 80px;
            padding: 20px;
            background-color: #000000;
            border-radius: 7px;
            display: grid;
            grid-template-columns: 1.3fr 6fr 0.5fr;
            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.08);
        }

        .inner-container p:first-child {
            color: #e0dfef;
            font-weight: 600;
            font-size: 20px;
        }

        .inner-container p:last-child {
            font-size: 14px;
            font-weight: 400;
            color: #9a9a9a;
        }

        .toast button {
            align-self: flex-start;
            background-color: transparent;
            font-size: 20px;
            color: #9a9a9a;
            line-height: 0;
            cursor: pointer;
            padding: 10px;
            margin-right: -10px;
        }
    </style>
{% endblock %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li class="active">
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell '></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block titleshit %}
    Alerts
{% endblock %}

{% block titleshit2 %}
    Alerts
{% endblock %}

{% block main %}
    <div class="wrapper">
        {% for alert in alerts_list %}
            <div class="accordion" id="accordionPanelsStayOpenExample">
                <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="toast success d-flex align-items-center accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{alert.id}}" aria-expanded="true" aria-controls="panelsStayOpen-collapse{{alert.id}}">
                                <div class="outer-container">
                                    <i class="fas fa-check-circle"></i>
                                </div>
                                <div class="inner-container ms-3">
                                    <p class="mb-0">{{alert.alertname}}</p>
                                    <p class="mb-0">Drone : {{alert.dronetarget}}</p>
                                </div>
                            </button>
                        </h2>
                    <div id="panelsStayOpen-collapse{{alert.id}}" class="accordion-collapse collapse">
                        <div class="accordion-body">
                            {{alert.alertdescription}}
                        </div>
                    </div>
                </div>  
                {% if alert.unread_alerts == True %}
                        <span class="position-absolute translate-middle p-2 bg-danger border border-light rounded-circle customtop">
                            <span class="visually-hidden">New alerts</span>
                        </span>
                {% endif %}
            </div>
        {% endfor %}
    </div>    
{% endblock %}

{% block sidebar %}
    
{% endblock %}

newstuff/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
	{% load bootstrap5 %}
	{% load functions %}
	{% bootstrap_css %}
	{% bootstrap_javascript %}

	{% block style %}
	{% endblock %}

	<style> 
		.button {
		border: none;
		color: rgba(255, 255, 255, 0);
		padding: 12px 30px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 4px 2px;
		transition-duration: 0.4s;
		cursor: pointer;
		}

		.button1 {
		background-color: white; 
		color: black; 
		border: 2px solid #04AA6D;
		}

		.button1:hover {
		background-color: #04AA6D;
		color: white;
		}

		.button2 {
		background-color: rgba(255, 255, 255, 0); 
		color: black; 
		border: 2px solid #008CBA;
		}

		.button2:hover {
		background-color: #008CBA;
		color: white;
		}

		ul.side-menu.top {
			margin: 0; /* or adjust as needed */
			padding: 0; /* or adjust as needed */
		}	
		
		ul.side-menu.bottom {
			margin: 0; /* or adjust as needed */
			padding: 0; /* or adjust as needed */
		}

		alert alert-success d-flex align-items-center {
			width: 150px;
			height: 50px;
		}

		profile-lo {
			margin: 0px 5px;
		}

		/* Position toasts at the bottom left of the screen */
        .toast-container {
            position: fixed;
            bottom: 0;
            left: 50%;
			transform: translate(393%, 0%);
            z-index: 1050;
            padding: 1rem;
        }

        .custom-img-size {
            max-width: 50px; /* Adjust as needed */
            max-height: 50px; /* Adjust as needed */
        }

		.btn-download {
			padding: 5px 0px;
		}

		.active {
			color: var(--blue);
		}
	</style>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<!-- My CSS -->
	<link rel="stylesheet" href="{% static 'css/style.css'%}">

	{% if user.is_authenticated %}
		{% for cuser in user_list %}
			{% if cuser.username == user.username and cuser.is_dark_theme %}
					<style>
						:root {
							--poppins: 'Poppins', sans-serif;
							--lato: 'Lato', sans-serif;

							--light: #060606;
							--blue: #3C91E6;
							--light-blue: #002930;
							--grey: #111111;
							--dark-grey: #555555;
							--dark: #cbd1c8;
							--red: #DB504A;
							--yellow: #FFCE26;
							--light-yellow: #391700;
							--orange: #FD7238;
							--light-orange: #2c1400;
						}
						.toast-header {
							background-color : #000000d9;
							color: #828c93;
						}
						.toast-body {
							background-color : #000000d9;
							color: #828c93;
						}
					</style>
					{% block darktheme %}
					{% endblock %}
			{% endif %}
		{% endfor %}
	{% endif %}

	<title>Agrisky</title>
</head>
<body>

	<!-- SIDEBAR -->
	<section id="sidebar" method="GET">
		<a href="{%url 'homeapp:dashboard' %}" class="brand">
			{% if user.is_authenticated %}
				{% for cuser in user_list %}
					{% if cuser.username == user.username and cuser.is_dark_theme %}
						<img class="text"; src = "{% static 'images/logosmol.png'%}"></i>
					{% elif cuser.username == user.username and not cuser.is_dark_theme %}
						<img class="text"; src = "{% static 'images/logosmolbutlight.png'%}"></i>
					{% endif %}
				{% endfor %}
			{% else %}
				<img class="text"; src = "{% static 'images/logosmolbutlight.png'%}"></i>
			{% endif %}
			<span class="text">Agrisky</span>
		</a>
		<ul class="side-menu top">
			{% block active %}

			{% endblock %}
		</ul>
		<ul class="side-menu bottom">
		{% block sidebar%}
		{% endblock %}
			{% if user.is_authenticated %}
				{% for cuser in user_list %}
					{% if cuser.username == user.username %}
						<form action="{% toggle_and_save_theme cuser request %}" id="theme-form" method="POST">
							{% csrf_token %}
							<li>
								<a id="theme-toggle" href="#" onclick="submitForm(event);">
									<i class='bx bxs-cog'></i>
									{% if cuser.is_dark_theme %}
										<span class="text">Light Theme</span>
									{% else %}
										<span class="text">Dark Theme</span>
									{% endif %}
								</a>
							</li>
						</form>
					{% endif %}
				{% endfor %}
			<li>
				<a href="{%url 'loginsapp:logoutuser' %}" class="logout">
					<i class='bx bxs-log-out-circle' ></i>
					<span class="text">Logout</span>
				</a>
			</li>
				{% for cuser in user_list %}
					{% if cuser.username == user.username and cuser.username == "bloomingyellow" and cuser.is_staff %}
						<li>
							<a href="{%url 'admin:index' %}">
								<i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
								<span class="text">Admin</span>
							</a>
						</li>
					{% endif %}
				{% endfor %}
			{% endif %}

		
		</ul>
	</section>
	<!-- SIDEBAR -->



	<!-- CONTENT -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<i class='bx bx-menu' ></i>
			<a href="#" class="nav-link">Categories</a>
			<form action="#">
				<div class="form-input">
					<input type="search" placeholder="Search...">
					<button type="submit" class="search-btn"><i class='bx bx-search' ></i></button>
				</div>
			</form>

			<input type="checkbox" id="switch-mode" hidden>
			<a href="{%url 'homeapp:alerts' %}" class="notification">
				<i class='bx bxs-bell' ></i>
				<span class="num">{{ unread_alerts }}</span>
			</a>
				
				{% if user.is_authenticated %}
					<a class="profile" href="{% url 'homeapp:profile' username=user.username %}"> 
						<img src="{% static 'images/avatar/' %}{{ user.username }}.png" alt="Avatar" href="#">	
					</a>				
				{% else %}
				<a class="profile" href= "{%url 'loginsapp:loginuser' %}"> 
					<button type="link" class="btn btn-outline-primary">Log In</button>
				</a>
				<a class="profile" href= "{%url 'loginsapp:registeruser' %}"> 
					<button type="link" class="btn btn-outline-secondary">Register</button>
				</a>
				{% endif %}
		</nav>
		<!-- NAVBAR -->

		{% block popup %}
		{% endblock %}
		<!-- MAIN -->
		<main>
			<div class="head-title">
				<div class="left">
					<h1>{% block titleshit %} {% endblock %}</h1>
					<ul class="breadcrumb">
						<li>
							<a href="{%url 'homeapp:dashboard'%}">Dashboard</a>
						</li>
						<li><i class='bx bx-chevron-right' ></i></li>
						<li>
							<a>{% block titleshit2 %} {% endblock %}</a>
						</li>
					</ul>
				</div>
				
				
				{% block addbutton %}
				{% endblock %}
				
				<a href="{% static 'images/MediDrone.pdf' %}" class="btn-download">
					<i class='bx bxs-cloud-download' ></i>
					<span class="text">Download Manual</span>
				</a>
			</div>
			{% block main %}
			{% endblock %}
			
		</main>
		<!-- MAIN -->
		 
		
		

		  <!-- TOASTS -->
		{% if messages %}
		    {% for message in messages %}
				<div aria-live="polite" aria-atomic="true" class="position-relative">
					<div class="toast-container bottom-0 start-0 p-3 timetohide">
						<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
							<div class="toast-header">
								<img src="{% static 'images/logosmol.png'%}" class="mr-3 rounded custom-img-size" alt="...">
								<strong class="me-auto">System</strong>
								<small class="text-body-secondary">just now</small>
								<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
							</div>
							<div class="toast-body">
								{{ message }}
							</div>
						</div>
						
					</div>
				</div>
			{% endfor %}
		{% endif %}
        <!-- TOASTS -->


	</section>
	<!-- CONTENT -->

	<script src="{% static 'js/script.js'%}"></script>

	<script>
		document.addEventListener('DOMContentLoaded', function () {
			var toastElList = [].slice.call(document.querySelectorAll('.timetohide'))
			var toastList = toastElList.map(function (toastEl) {
				return new bootstrap.Toast(toastEl, { delay: 5000 });
			});
			toastList.forEach(toast => toast.show());
		});
	</script>

	<script>
		function submitForm(event) {
			event.preventDefault();

			const form = document.getElementById('theme-form');
			const formData = new FormData(form);

			fetch(form.action, {
				method: 'POST',
				headers: {
					'X-CSRFToken': '{{ csrf_token }}',
				},
				body: formData
			})
			.then(response => {
				if (response.ok) {
					window.location.href = window.location.pathname; 
				} else {
					console.error('Fuck, it failed again...');
				}
			})
			.catch(error => console.error('Error:', error));
		}
	</script>

	{% block js %}
	{% endblock %}
</body>
</html>

newstuff/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li class="active">
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell '></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block titleshit %}
   Dashboard
{% endblock %}

{% block titleshit2 %}
   Home
{% endblock %}

{% block main %}
   

    <ul class="box-info">
        <li>
            <i class='bx bxs-calendar-check' ></i>
            <span class="text">
                <h3> {{ drone_active }} </h3>
                <p>Active Drone</p>
            </span>
        </li>
        <li>
            <i class='bx bxs-group' ></i>
            <span class="text">
                <h3> {{ drone_not_active }} </h3>
                <p>Inactive Drones</p>
            </span>
        </li>
        <li>
            <i class='bx bxs-dollar-circle' ></i>
            <span class="text">
                <h3>{{ unread_alerts }}</h3>
                <p>Alerts</p>
            </span>
        </li>
    </ul>


    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Drones</h3>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Drone</th>
                        <th>Last Connection Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for drone in drone_list %}
                        {% if drone.active %}
                            <tr>
                                <td>
                                    <img src="{% static 'images/drone.svg' %}">
                                    <p>{{drone.dronename}}</p>
                                </td>
                                <td>{{currenttime}}</td>
                                <td><span class="status completed">Online</span></td>
                            </tr>
                        {% else %}
                            <tr>
                                <td>
                                    <img src="{% static 'images/drone.svg' %}">
                                    <p>{{drone.dronename}}</p>
                                </td>
                                <td>{{drone.lastconnectiondate.date}}</td>
                                <td><span class="status pending">Pending Connection</span></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="todo">
            <div class="head">
                <h3>Recent Reports</h3>
            </div>
            <ul class="todo-list">
                {% for report in reports_list %}
                    {% if report.writer.username == "Admin" %}
                    <li class="completed">
                        <p>{{report.reportname}}</p>
                        <i class='bx bx-dots-vertical-rounded'></i>
                    </li>
                    {% else %}
                    <li class="not-completed">
                        <p>{{report.reportname}}</p>
                        <i class='bx bx-dots-vertical-rounded'}"></i>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block sidebar %}

{% endblock %}

newstuff/templates/reports.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' ></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li class="active">
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell' ></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block titleshit %}
    Reports
{% endblock %}

{% block titleshit2 %}
   Reports
{% endblock %}

{% block main %}
{% endblock %}

{% block sidebar %}
    
{% endblock %}